### ISSUE TITLE
Create seed data for database

### ISSUE THREAD

**Issue by akatheduelist** [Lemelisk271/welp-group-project#15]
- [x] Seed users - @akatheduelist 
- [x] Seed businesses - @akatheduelist 
- [x] Seed business_images - @akatheduelist 
- [x] Seed amenities - @Lemelisk271
- [x] Seed business_amenity - @Lemelisk271
- [x] Seed reviews - @Lemelisk271
- [x] Seed days - @Lemelisk271
- [x] Seed business_hours - @Lemelisk271 
- [x] Seed questions - @MasoodMS95 @darocket34 
- [x] Seed answers - @MasoodMS95 @darocket34 
- [x] Seed votes - @MasoodMS95 @darocket34 
- [x] Seed review_comments - @MasoodMS95 @darocket34 
- [x] Seed categories - @MasoodMS95 @darocket34 
- [x] Seed business_categories - @MasoodMS95 @darocket34

**Comment by akatheduelist** [comment]
Faker component documentation:
https://github.com/joke2k/faker

**Comment by darocket34** [comment]
we need to discuss date formats for our seed for questions, answers, and reviews
